#配置文件
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/123

server:
  port: 9002
spring:
  application:
    name: service-one
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      enabled: true
      fail-fast: true
      label: master
      name: config-service-one
      profile: dev
      uri: http://localhost:8200


